-- ============================================================================
-- Hospital Incident Analytics — PostgreSQL Database Schema
-- ============================================================================
-- Description : Relational schema for enterprise IT incident/ticket tracking.
--               Follows a star-schema-inspired layout with two dimension tables
--               (dim_agents, dim_categories) and one fact table (fact_tickets).
--
-- Author      : Auto-generated by Antigravity
-- Created     : 2026-05-28
-- ============================================================================

-- Drop existing objects (idempotent re-runs) ------------------------------------
DROP TABLE IF EXISTS fact_tickets  CASCADE;
DROP TABLE IF EXISTS dim_agents    CASCADE;
DROP TABLE IF EXISTS dim_categories CASCADE;

-- ============================================================================
-- 1. DIMENSION: Agents
-- ============================================================================
CREATE TABLE dim_agents (
    agent_id   SERIAL       PRIMARY KEY,
    agent_name VARCHAR(120) NOT NULL,
    tier       VARCHAR(30)  NOT NULL
        CHECK (tier IN ('Tier 1', 'Tier 2', 'Tier 3'))
);

COMMENT ON TABLE  dim_agents          IS 'Support agents responsible for resolving incidents.';
COMMENT ON COLUMN dim_agents.tier     IS 'Escalation tier: Tier 1 (L1), Tier 2 (L2), Tier 3 (L3).';

-- ============================================================================
-- 2. DIMENSION: Categories
-- ============================================================================
CREATE TABLE dim_categories (
    category_id       SERIAL       PRIMARY KEY,
    category_name     VARCHAR(100) NOT NULL,
    department_target VARCHAR(100) NOT NULL
);

COMMENT ON TABLE  dim_categories                    IS 'Incident categories mapped to owning departments.';
COMMENT ON COLUMN dim_categories.department_target   IS 'Department responsible for this category of incidents.';

-- ============================================================================
-- 3. FACT: Tickets
-- ============================================================================
CREATE TABLE fact_tickets (
    ticket_id   SERIAL        PRIMARY KEY,
    created_at  TIMESTAMP     NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMP,
    severity    VARCHAR(20)   NOT NULL
        CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    status      VARCHAR(20)   NOT NULL
        CHECK (status IN ('Open', 'In Progress', 'Resolved', 'Closed', 'Escalated')),
    agent_id    INT           NOT NULL,
    category_id INT           NOT NULL,
    branch_id   INT           NOT NULL,
    sla_met     BOOLEAN       NOT NULL DEFAULT TRUE,

    -- Foreign-key constraints ------------------------------------------------
    CONSTRAINT fk_tickets_agent
        FOREIGN KEY (agent_id)
        REFERENCES dim_agents (agent_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_tickets_category
        FOREIGN KEY (category_id)
        REFERENCES dim_categories (category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- Performance indexes --------------------------------------------------------
CREATE INDEX idx_tickets_created_at  ON fact_tickets (created_at);
CREATE INDEX idx_tickets_severity    ON fact_tickets (severity);
CREATE INDEX idx_tickets_status      ON fact_tickets (status);
CREATE INDEX idx_tickets_agent       ON fact_tickets (agent_id);
CREATE INDEX idx_tickets_category    ON fact_tickets (category_id);
CREATE INDEX idx_tickets_branch      ON fact_tickets (branch_id);
CREATE INDEX idx_tickets_sla         ON fact_tickets (sla_met);

COMMENT ON TABLE  fact_tickets            IS 'Core fact table recording every IT incident ticket.';
COMMENT ON COLUMN fact_tickets.branch_id  IS 'Enterprise branch / site where the incident originated.';
COMMENT ON COLUMN fact_tickets.sla_met    IS 'Whether the ticket was resolved within the SLA window.';
